import { FuelTypeEnum, LocationEnum } from '../types';

// kgCO2e/kWh
export const EMISSIONS_FACTORS: Record<string, number | Record<string, number>> = {
  [FuelTypeEnum.NaturalGas]: 0.19,
  [FuelTypeEnum.Lpg]: 0.22,
  [FuelTypeEnum.Wood]: 0.40,
  [FuelTypeEnum.Petrol]: 0.24,
  [FuelTypeEnum.Diesel]: 0.25,
  [FuelTypeEnum.Solar]: 0,
  [FuelTypeEnum.Electricity]: {
    [LocationEnum.Victoria]: 0.30,
    [LocationEnum.NewSouthWales]: 0.26,
    [LocationEnum.NorthernTerritory]: 0.20,
    [LocationEnum.AustralianCapitalTerritory]: 0.26,
    [LocationEnum.Tasmania]: 0.05,
    [LocationEnum.WesternAustralia]: 0.22,
    [LocationEnum.SouthAustralia]: 0.09,
    [LocationEnum.Queensland]: 0.27,
  },
};

// $/kWh
export const COST_PER_FUEL_KWH_TODAY: Record<string, Record<string, any>> = {
  [FuelTypeEnum.Electricity]: {
    [LocationEnum.Victoria]: { volume_rate: 0.27, off_peak: 0.18 },
    [LocationEnum.NewSouthWales]: { volume_rate: 0.34, off_peak: 0.22 },
    [LocationEnum.NorthernTerritory]: { volume_rate: 0.28, off_peak: 0.19 },
    [LocationEnum.AustralianCapitalTerritory]: { volume_rate: 0.26, off_peak: 0.17 },
    [LocationEnum.Tasmania]: { volume_rate: 0.30, off_peak: 0.20 },
    [LocationEnum.WesternAustralia]: { volume_rate: 0.31, off_peak: 0.21 },
    [LocationEnum.SouthAustralia]: { volume_rate: 0.44, off_peak: 0.29 },
    [LocationEnum.Queensland]: { volume_rate: 0.32, off_peak: 0.21 },
  },
  [FuelTypeEnum.NaturalGas]: {
    [LocationEnum.Victoria]: 0.133,
    [LocationEnum.NewSouthWales]: 0.153,
    [LocationEnum.NorthernTerritory]: 0.146,
    [LocationEnum.AustralianCapitalTerritory]: 0.159,
    [LocationEnum.Tasmania]: 0.194,
    [LocationEnum.WesternAustralia]: 0.115,
    [LocationEnum.SouthAustralia]: 0.202,
    [LocationEnum.Queensland]: 0.209,
  },
  [FuelTypeEnum.Lpg]: {
    [LocationEnum.Victoria]: 0.26,
    [LocationEnum.NewSouthWales]: 0.31,
    [LocationEnum.NorthernTerritory]: 0.40,
    [LocationEnum.AustralianCapitalTerritory]: 0.28,
    [LocationEnum.Tasmania]: 0.24,
    [LocationEnum.WesternAustralia]: 0.22,
    [LocationEnum.SouthAustralia]: 0.30,
    [LocationEnum.Queensland]: 0.30,
  },
  [FuelTypeEnum.Wood]: {
    [LocationEnum.Victoria]: 0.110,
    [LocationEnum.NewSouthWales]: 0.140,
    [LocationEnum.NorthernTerritory]: 0.151,
    [LocationEnum.AustralianCapitalTerritory]: 0.094,
    [LocationEnum.Tasmania]: 0.067,
    [LocationEnum.WesternAustralia]: 0.140,
    [LocationEnum.SouthAustralia]: 0.111,
    [LocationEnum.Queensland]: 0.151,
  },
  [FuelTypeEnum.Petrol]: {
    [LocationEnum.Victoria]: 0.199,
    [LocationEnum.NewSouthWales]: 0.200,
    [LocationEnum.NorthernTerritory]: 0.208,
    [LocationEnum.AustralianCapitalTerritory]: 0.200,
    [LocationEnum.Tasmania]: 0.199,
    [LocationEnum.WesternAustralia]: 0.192,
    [LocationEnum.SouthAustralia]: 0.193,
    [LocationEnum.Queensland]: 0.202,
  },
  [FuelTypeEnum.Diesel]: {
    [LocationEnum.Victoria]: 0.18,
    [LocationEnum.NewSouthWales]: 0.18,
    [LocationEnum.NorthernTerritory]: 0.20,
    [LocationEnum.AustralianCapitalTerritory]: 0.18,
    [LocationEnum.Tasmania]: 0.18,
    [LocationEnum.WesternAustralia]: 0.17,
    [LocationEnum.SouthAustralia]: 0.18,
    [LocationEnum.Queensland]: 0.18,
  },
  [FuelTypeEnum.Solar]: {
    [LocationEnum.Victoria]: 0,
    [LocationEnum.NewSouthWales]: 0,
    [LocationEnum.NorthernTerritory]: 0,
    [LocationEnum.AustralianCapitalTerritory]: 0,
    [LocationEnum.Tasmania]: 0,
    [LocationEnum.WesternAustralia]: 0,
    [LocationEnum.SouthAustralia]: 0,
    [LocationEnum.Queensland]: 0,
  },
};

// $/year
export const FIXED_COSTS_PER_YEAR_2024: Record<string, Record<string, number>> = {
  [FuelTypeEnum.Electricity]: {
    [LocationEnum.Victoria]: 396,
    [LocationEnum.NewSouthWales]: 465,
    [LocationEnum.NorthernTerritory]: 210,
    [LocationEnum.AustralianCapitalTerritory]: 441,
    [LocationEnum.Tasmania]: 435,
    [LocationEnum.WesternAustralia]: 414,
    [LocationEnum.SouthAustralia]: 415,
    [LocationEnum.Queensland]: 450,
  },
  [FuelTypeEnum.NaturalGas]: {
    [LocationEnum.Victoria]: 296,
    [LocationEnum.NewSouthWales]: 244,
    [LocationEnum.NorthernTerritory]: 247,
    [LocationEnum.AustralianCapitalTerritory]: 260,
    [LocationEnum.Tasmania]: 235,
    [LocationEnum.WesternAustralia]: 80,
    [LocationEnum.SouthAustralia]: 297,
    [LocationEnum.Queensland]: 247,
  },
  [FuelTypeEnum.Lpg]: {
    [LocationEnum.Victoria]: 96.0,
    [LocationEnum.NewSouthWales]: 96.0,
    [LocationEnum.NorthernTerritory]: 105.0,
    [LocationEnum.AustralianCapitalTerritory]: 96.0,
    [LocationEnum.Tasmania]: 96.0,
    [LocationEnum.WesternAustralia]: 90.0,
    [LocationEnum.SouthAustralia]: 99.0,
    [LocationEnum.Queensland]: 95.0,
  },
};

// Average over next 15 years, $/kWh
export const COST_PER_FUEL_KWH_AVG_15_YEARS: Record<string, Record<string, number>> = {
  [FuelTypeEnum.Electricity]: {
    [LocationEnum.Victoria]: 0.31,
    [LocationEnum.NewSouthWales]: 0.41,
    [LocationEnum.NorthernTerritory]: 0.28,
    [LocationEnum.AustralianCapitalTerritory]: 0.30,
    [LocationEnum.Tasmania]: 0.36,
    [LocationEnum.WesternAustralia]: 0.38,
    [LocationEnum.SouthAustralia]: 0.54,
    [LocationEnum.Queensland]: 0.55,
  },
  [FuelTypeEnum.NaturalGas]: {
    [LocationEnum.Victoria]: 0.22,
    [LocationEnum.NewSouthWales]: 0.19,
    [LocationEnum.NorthernTerritory]: 0.19,
    [LocationEnum.AustralianCapitalTerritory]: 0.21,
    [LocationEnum.Tasmania]: 0.26,
    [LocationEnum.WesternAustralia]: 0.18,
    [LocationEnum.SouthAustralia]: 0.25,
    [LocationEnum.Queensland]: 0.247,
  },
  [FuelTypeEnum.Lpg]: {
    [LocationEnum.Victoria]: 0.35,
    [LocationEnum.NewSouthWales]: 0.38,
    [LocationEnum.NorthernTerritory]: 0.41,
    [LocationEnum.AustralianCapitalTerritory]: 0.36,
    [LocationEnum.Tasmania]: 0.27,
    [LocationEnum.WesternAustralia]: 0.26,
    [LocationEnum.SouthAustralia]: 0.38,
    [LocationEnum.Queensland]: 0.35,
  },
  [FuelTypeEnum.Wood]: {
    [LocationEnum.Victoria]: 0.15,
    [LocationEnum.NewSouthWales]: 0.17,
    [LocationEnum.NorthernTerritory]: 0.16,
    [LocationEnum.AustralianCapitalTerritory]: 0.12,
    [LocationEnum.Tasmania]: 0.08,
    [LocationEnum.WesternAustralia]: 0.17,
    [LocationEnum.SouthAustralia]: 0.14,
    [LocationEnum.Queensland]: 0.18,
  },
  [FuelTypeEnum.Petrol]: {
    [LocationEnum.Victoria]: 0.22,
    [LocationEnum.NewSouthWales]: 0.22,
    [LocationEnum.NorthernTerritory]: 0.21,
    [LocationEnum.AustralianCapitalTerritory]: 0.22,
    [LocationEnum.Tasmania]: 0.21,
    [LocationEnum.WesternAustralia]: 0.21,
    [LocationEnum.SouthAustralia]: 0.21,
    [LocationEnum.Queensland]: 0.23,
  },
  [FuelTypeEnum.Diesel]: {
    [LocationEnum.Victoria]: 0.20,
    [LocationEnum.NewSouthWales]: 0.20,
    [LocationEnum.NorthernTerritory]: 0.20,
    [LocationEnum.AustralianCapitalTerritory]: 0.19,
    [LocationEnum.Tasmania]: 0.19,
    [LocationEnum.WesternAustralia]: 0.19,
    [LocationEnum.SouthAustralia]: 0.19,
    [LocationEnum.Queensland]: 0.20,
  },
  [FuelTypeEnum.Solar]: {
    [LocationEnum.Victoria]: 0,
    [LocationEnum.NewSouthWales]: 0,
    [LocationEnum.NorthernTerritory]: 0,
    [LocationEnum.AustralianCapitalTerritory]: 0,
    [LocationEnum.Tasmania]: 0,
    [LocationEnum.WesternAustralia]: 0,
    [LocationEnum.SouthAustralia]: 0,
    [LocationEnum.Queensland]: 0,
  },
};

// $/year average over next 15 years
export const FIXED_COSTS_PER_YEAR_AVG_15_YEARS: Record<string, Record<string, number>> = {
  [FuelTypeEnum.Electricity]: {
    [LocationEnum.Victoria]: 446.05,
    [LocationEnum.NewSouthWales]: 562.08,
    [LocationEnum.NorthernTerritory]: 205.94,
    [LocationEnum.AustralianCapitalTerritory]: 511.12,
    [LocationEnum.Tasmania]: 517.42,
    [LocationEnum.WesternAustralia]: 509.48,
    [LocationEnum.SouthAustralia]: 507.18,
    [LocationEnum.Queensland]: 777.94,
  },
  [FuelTypeEnum.NaturalGas]: {
    [LocationEnum.Victoria]: 265.21,
    [LocationEnum.NewSouthWales]: 300.40,
    [LocationEnum.NorthernTerritory]: 314.22,
    [LocationEnum.AustralianCapitalTerritory]: 337.02,
    [LocationEnum.Tasmania]: 375.07,
    [LocationEnum.WesternAustralia]: 398.60,
    [LocationEnum.SouthAustralia]: 291.28,
    [LocationEnum.Queensland]: 291.28,
  },
  [FuelTypeEnum.Lpg]: {
    [LocationEnum.Victoria]: 129.28,
    [LocationEnum.NewSouthWales]: 118.16,
    [LocationEnum.NorthernTerritory]: 108.22,
    [LocationEnum.AustralianCapitalTerritory]: 124.58,
    [LocationEnum.Tasmania]: 108.12,
    [LocationEnum.WesternAustralia]: 108.54,
    [LocationEnum.SouthAustralia]: 125.03,
    [LocationEnum.Queensland]: 112.17,
  },
};
